#!/usr/bin/env python3
"""Writes src/syntax_tags.c from the vendored grammars' queries/tags.scm.

    python3 tools/gen_syntax_tags.py        (from cli/kb-cli)

Each tags.scm is split into its top-level patterns, and the patterns are
written out as C strings per language, so kb carries the queries inside the
binary and can compile them pattern by pattern (a pattern that names a node
this grammar lacks is skipped, not fatal). TypeScript and TSX take the
JavaScript patterns and their own, as upstream's tags do. Assembly has no
tags.scm: its labels are its definitions, found without a query.

Run it again after updating a grammar (src/third_party/TREE-SITTER.md).
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))
TP = os.path.join(HERE, "..", "src", "third_party")


def patterns(path):
    text = open(path).read()
    out, depth, cur, i = [], 0, [], 0
    while i < len(text):
        c = text[i]
        if c == ";" and depth == 0:
            while i < len(text) and text[i] != "\n":
                i += 1
            continue
        if c == ";":  # a comment inside a pattern
            while i < len(text) and text[i] != "\n":
                i += 1
            cur.append("\n")
            continue
        if c == '"':
            j = i + 1
            while j < len(text) and text[j] != '"':
                j += 2 if text[j] == "\\" else 1
            cur.append(text[i:j + 1])
            i = j + 1
            continue
        if c in "([":
            depth += 1
        if c in ")]":
            depth -= 1
        cur.append(c)
        i += 1
        if depth == 0 and c in ")]":
            # A pattern may be followed by captures (@definition.x) and
            # predicates in its own parens are inside it already.
            j = i
            while j < len(text) and text[j] in " \t":
                j += 1
            while j < len(text) and text[j] == "@":
                k = j
                while k < len(text) and not text[k].isspace():
                    k += 1
                cur.append(" " + text[j:k])
                j = k
                while j < len(text) and text[j] in " \t":
                    j += 1
            i = j
            p = "".join(cur).strip()
            if p:
                out.append(p)
            cur = []
    return [p for p in out if "@definition" in p]


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def main():
    js = patterns(os.path.join(TP, "tree-sitter-javascript", "queries", "tags.scm"))
    ts = patterns(os.path.join(TP, "tree-sitter-typescript", "queries", "tags.scm"))
    langs = [
        ("SYNTAX_C", patterns(os.path.join(TP, "tree-sitter-c", "queries", "tags.scm"))),
        ("SYNTAX_TYPESCRIPT", js + ts),
        ("SYNTAX_TSX", js + ts),
        ("SYNTAX_JAVASCRIPT", js),
        ("SYNTAX_PYTHON", patterns(os.path.join(TP, "tree-sitter-python", "queries", "tags.scm"))),
        ("SYNTAX_GO", patterns(os.path.join(TP, "tree-sitter-go", "queries", "tags.scm"))),
        ("SYNTAX_RUST", patterns(os.path.join(TP, "tree-sitter-rust", "queries", "tags.scm"))),
    ]
    lines = ["/* GENERATED by tools/gen_syntax_tags.py from the vendored grammars'",
             " * queries/tags.scm (the definitions only). Do not edit; run the script. */",
             "", '#include "syntax.h"', "", "#include <stddef.h>", ""]
    for name, pats in langs:
        lines.append(f"static const char *const {name.lower()}_tags[] = {{")
        for p in pats:
            lines.append(f"    {c_string(p)},")
        lines.append("    NULL};")
        lines.append("")
    lines.append("const char *const *const SYNTAX_TAGS[SYNTAX_COUNT] = {")
    for name, _ in langs:
        lines.append(f"    [{name}] = {name.lower()}_tags,")
    lines.append("};")
    out = os.path.join(HERE, "..", "src", "syntax_tags.c")
    open(out, "w").write("\n".join(lines) + "\n")
    for name, pats in langs:
        print(f"{name}: {len(pats)} definition patterns")


if __name__ == "__main__":
    main()
