#include "dirscan.h"

#include "chunk.h"
#include "gitignore.h"
#include "platform.h"

#include <ctype.h>
#include <stdio.h>
#include <string.h>

/* ---- the name rules ----------------------------------------------------- */

static bool ends_with(const char *s, const char *suffix) {
    size_t n = strlen(s), m = strlen(suffix);
    return n >= m && strcmp(s + n - m, suffix) == 0;
}

/* Directories that hold code the workspace depends on rather than code it
 * wrote. .gitignore usually keeps these out already; this is for the tree
 * that commits them. */
static bool vendored_dir(const char *name) {
    static const char *const names[] = {
        "node_modules", "vendor",   "third_party", "third-party",
        "bower_components", "__pycache__", "venv", "site-packages", NULL};
    for (int32_t i = 0; names[i]; i++)
        if (strcmp(name, names[i]) == 0)
            return true;
    return false;
}

bool dir_name_generated(const char *name) {
    static const char *const names[] = {
        "package-lock.json", "npm-shrinkwrap.json", "pnpm-lock.yaml",
        "yarn.lock",         "Cargo.lock",          "go.sum",
        "poetry.lock",       "composer.lock",       "Gemfile.lock",
        "Pipfile.lock",      NULL};
    static const char *const suffixes[] = {
        ".min.js", ".min.mjs", ".min.css", ".bundle.js", ".pb.go", "_pb2.py",
        ".pb.h",   ".pb.cc",   ".g.dart",  ".designer.cs", NULL};
    for (int32_t i = 0; names[i]; i++)
        if (strcmp(name, names[i]) == 0)
            return true;
    for (int32_t i = 0; suffixes[i]; i++)
        if (ends_with(name, suffixes[i]))
            return true;
    return false;
}

const char *dir_file_mime(const char *name) {
    static const struct {
        const char *name;
        const char *mime;
    } whole[] = {{"Makefile", "text/x-makefile"},
                 {"makefile", "text/x-makefile"},
                 {"GNUmakefile", "text/x-makefile"},
                 {"Dockerfile", "text/x-dockerfile"},
                 {"CMakeLists.txt", "text/x-cmake"},
                 {"README", "text/plain"},
                 {"CHANGELOG", "text/plain"},
                 {"CONTRIBUTING", "text/plain"},
                 {NULL, NULL}};
    for (int32_t i = 0; whole[i].name; i++)
        if (strcmp(name, whole[i].name) == 0)
            return whole[i].mime;
    return chunk_mime_from_path(name);
}

static bool has_icase(const char *s, size_t n, const char *needle) {
    size_t m = strlen(needle);
    for (size_t i = 0; i + m <= n; i++) {
        size_t k = 0;
        while (k < m && tolower((unsigned char)s[i + k]) == needle[k])
            k++;
        if (k == m)
            return true;
    }
    return false;
}

/* The markers code generators put at the top of what they write: Go's
 * "Code generated ... DO NOT EDIT.", Facebook's `@generated`, and the prose
 * forms. Only the first five lines are read, so documentation that mentions
 * the phrase further down is still filed. */
bool dir_text_generated(const char *text, size_t len) {
    size_t n = 0;
    for (int32_t lines = 0; n < len && lines < 5; n++)
        if (text[n] == '\n')
            lines++;
    static const char *const markers[] = {
        "@generated", "do not edit", "auto-generated", "autogenerated",
        "automatically generated", NULL};
    for (int32_t i = 0; markers[i]; i++)
        if (has_icase(text, n, markers[i]))
            return true;
    return false;
}

/* Valid UTF-8 without a NUL byte: what a text file is, as far as kb can
 * tell without being told. */
static bool is_text(const unsigned char *s, size_t n) {
    for (size_t i = 0; i < n;) {
        unsigned char c = s[i];
        if (c == 0)
            return false;
        if (c < 0x80) {
            i++;
            continue;
        }
        size_t k;
        uint32_t min;
        uint32_t cp;
        if ((c & 0xE0) == 0xC0) {
            k = 1, min = 0x80, cp = c & 0x1F;
        } else if ((c & 0xF0) == 0xE0) {
            k = 2, min = 0x800, cp = c & 0x0F;
        } else if ((c & 0xF8) == 0xF0) {
            k = 3, min = 0x10000, cp = c & 0x07;
        } else {
            return false;
        }
        for (size_t j = 1; j <= k; j++) {
            if (i + j >= n || (s[i + j] & 0xC0) != 0x80)
                return false;
            cp = (cp << 6) | (s[i + j] & 0x3F);
        }
        if (cp < min || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF))
            return false;
        i += k + 1;
    }
    return true;
}

/* ---- the walk ----------------------------------------------------------- */

typedef struct {
    Arena *a;
    const char *root;   /* absolute */
    const char *prefix; /* root relative to the top; "" when they are one */
    const char *top;
    GitIgnore *ig;
    DirScan *out;
} Walk;

static const char *top_rel(const Walk *w, const char *rel) {
    return w->prefix[0] ? arena_printf(w->a, "%s/%s", w->prefix, rel) : rel;
}

static WalkAction visit(const char *rel, bool is_dir, void *ud) {
    Walk *w = (Walk *)ud;
    DirScan *o = w->out;
    const char *slash = strrchr(rel, '/');
    const char *name = slash ? slash + 1 : rel;
    if (name[0] == '.') {
        o->hidden++;
        return is_dir ? WALK_SKIP_DIR : WALK_CONT;
    }
    const char *tr = top_rel(w, rel);
    if (gitignore_match(w->ig, tr, is_dir)) {
        o->ignored++;
        return is_dir ? WALK_SKIP_DIR : WALK_CONT;
    }
    if (is_dir) {
        if (vendored_dir(name)) {
            o->vendored++;
            return WALK_SKIP_DIR;
        }
        /* Its own .gitignore applies to everything below it, and the walk
         * is pre-order, so it is read before any of that is visited. */
        gitignore_load(w->ig, w->top, tr);
        return WALK_CONT;
    }
    const char *mime = dir_file_mime(name);
    if (!mime) {
        o->other++;
        return WALK_CONT;
    }
    if (dir_name_generated(name)) {
        o->generated++;
        return WALK_CONT;
    }
    char *path = arena_printf(w->a, "%s/%s", w->root, rel);
    uint64_t size = 0;
    if (!plat_file_size(path, &size)) {
        o->unreadable++;
        return WALK_CONT;
    }
    bool json = strcmp(mime, "application/json") == 0;
    if (size > (json ? KB_DIR_MAX_JSON_BYTES : KB_DIR_MAX_BYTES)) {
        o->large++;
        return WALK_CONT;
    }
    char *text;
    size_t len;
    if (!plat_read_file_max(w->a, path, &text, &len, KB_DIR_MAX_BYTES)) {
        o->unreadable++;
        return WALK_CONT;
    }
    if (len == 0 || !is_text((const unsigned char *)text, len)) {
        /* An empty file has nothing to find; it is counted with the files
         * that are not text because neither can be filed. */
        o->binary++;
        return WALK_CONT;
    }
    if (dir_text_generated(text, len)) {
        o->generated++;
        return WALK_CONT;
    }
    ARENA_GROW(w->a, o->v, o->n, o->cap, DirFile);
    DirFile *f = &o->v[o->n++];
    f->rel = arena_strdup(w->a, rel);
    f->mime = mime;
    f->content = text;
    f->len = len;
    return WALK_CONT;
}

/* The nearest directory at or above `dir` holding `.git` (a directory, or a
 * file in a worktree). */
static const char *find_top(Arena *a, const char *dir) {
    char *p = arena_strdup(a, dir);
    for (;;) {
        char *git = arena_printf(a, "%s/.git", p);
        if (plat_is_dir(git) || plat_is_file(git))
            return p;
        char *slash = strrchr(p, '/');
        if (!slash || slash == p)
            return NULL;
        *slash = '\0';
    }
}

bool dir_scan(Arena *a, const char *root, DirScan *out, char *err, size_t errsz) {
    memset(out, 0, sizeof *out);
    if (!plat_is_dir(root)) {
        snprintf(err, errsz, "%s is not a directory", root);
        return false;
    }
    const char *top = find_top(a, root);
    if (!top)
        top = root;
    const char *prefix = root + strlen(top);
    if (*prefix == '/')
        prefix++;
    out->top = top;

    GitIgnore *ig = gitignore_new(a);
    if (top != root) {
        char *text;
        size_t len;
        char *exclude = arena_printf(a, "%s/.git/info/exclude", top);
        if (plat_is_file(exclude) && plat_read_file(a, exclude, &text, &len))
            gitignore_add(ig, "", text, len);
    }
    /* Every .gitignore from the top down to the folder itself. */
    gitignore_load(ig, top, "");
    for (const char *p = prefix; *p;) {
        const char *slash = strchr(p, '/');
        size_t upto = slash ? (size_t)(slash - prefix) : strlen(prefix);
        gitignore_load(ig, top, arena_strndup(a, prefix, upto));
        if (!slash)
            break;
        p = slash + 1;
    }

    Walk w = {a, root, prefix, top, ig, out};
    if (!plat_walk(a, root, visit, &w)) {
        snprintf(err, errsz, "cannot walk %s", root);
        return false;
    }
    return true;
}
