/* GENERATED by tools/gen_syntax_tags.py from the vendored grammars'
 * queries/tags.scm (the definitions only). Do not edit; run the script. */

#include "syntax.h"

#include <stddef.h>

static const char *const syntax_c_tags[] = {
    "(struct_specifier name: (type_identifier) @name body:(_)) @definition.class",
    "(declaration type: (union_specifier name: (type_identifier) @name)) @definition.class",
    "(function_declarator declarator: (identifier) @name) @definition.function",
    "(type_definition declarator: (type_identifier) @name) @definition.type",
    "(enum_specifier name: (type_identifier) @name) @definition.type",
    NULL};

static const char *const syntax_typescript_tags[] = {
    "(\n  (comment)* @doc\n  .\n  (method_definition\n    name: (property_identifier) @name) @definition.method\n  (#not-eq? @name \"constructor\")\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.method)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (class\n      name: (_) @name)\n    (class_declaration\n      name: (_) @name)\n  ] @definition.class\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.class)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (function_expression\n      name: (identifier) @name)\n    (function_declaration\n      name: (identifier) @name)\n    (generator_function\n      name: (identifier) @name)\n    (generator_function_declaration\n      name: (identifier) @name)\n  ] @definition.function\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(assignment_expression\n  left: [\n    (identifier) @name\n    (member_expression\n      property: (property_identifier) @name)\n  ]\n  right: [(arrow_function) (function_expression)]\n) @definition.function",
    "(pair\n  key: (property_identifier) @name\n  value: [(arrow_function) (function_expression)]) @definition.function",
    "(export_statement value: (assignment_expression left: (identifier) @name right: ([\n (number)\n (string)\n (identifier)\n (undefined)\n (null)\n (new_expression)\n (binary_expression)\n (call_expression)\n]))) @definition.constant",
    "(function_signature\n  name: (identifier) @name) @definition.function",
    "(method_signature\n  name: (property_identifier) @name) @definition.method",
    "(abstract_method_signature\n  name: (property_identifier) @name) @definition.method",
    "(abstract_class_declaration\n  name: (type_identifier) @name) @definition.class",
    "(module\n  name: (identifier) @name) @definition.module",
    "(interface_declaration\n  name: (type_identifier) @name) @definition.interface",
    NULL};

static const char *const syntax_tsx_tags[] = {
    "(\n  (comment)* @doc\n  .\n  (method_definition\n    name: (property_identifier) @name) @definition.method\n  (#not-eq? @name \"constructor\")\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.method)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (class\n      name: (_) @name)\n    (class_declaration\n      name: (_) @name)\n  ] @definition.class\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.class)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (function_expression\n      name: (identifier) @name)\n    (function_declaration\n      name: (identifier) @name)\n    (generator_function\n      name: (identifier) @name)\n    (generator_function_declaration\n      name: (identifier) @name)\n  ] @definition.function\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(assignment_expression\n  left: [\n    (identifier) @name\n    (member_expression\n      property: (property_identifier) @name)\n  ]\n  right: [(arrow_function) (function_expression)]\n) @definition.function",
    "(pair\n  key: (property_identifier) @name\n  value: [(arrow_function) (function_expression)]) @definition.function",
    "(export_statement value: (assignment_expression left: (identifier) @name right: ([\n (number)\n (string)\n (identifier)\n (undefined)\n (null)\n (new_expression)\n (binary_expression)\n (call_expression)\n]))) @definition.constant",
    "(function_signature\n  name: (identifier) @name) @definition.function",
    "(method_signature\n  name: (property_identifier) @name) @definition.method",
    "(abstract_method_signature\n  name: (property_identifier) @name) @definition.method",
    "(abstract_class_declaration\n  name: (type_identifier) @name) @definition.class",
    "(module\n  name: (identifier) @name) @definition.module",
    "(interface_declaration\n  name: (type_identifier) @name) @definition.interface",
    NULL};

static const char *const syntax_javascript_tags[] = {
    "(\n  (comment)* @doc\n  .\n  (method_definition\n    name: (property_identifier) @name) @definition.method\n  (#not-eq? @name \"constructor\")\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.method)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (class\n      name: (_) @name)\n    (class_declaration\n      name: (_) @name)\n  ] @definition.class\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.class)\n)",
    "(\n  (comment)* @doc\n  .\n  [\n    (function_expression\n      name: (identifier) @name)\n    (function_declaration\n      name: (identifier) @name)\n    (generator_function\n      name: (identifier) @name)\n    (generator_function_declaration\n      name: (identifier) @name)\n  ] @definition.function\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (lexical_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (variable_declaration\n    (variable_declarator\n      name: (identifier) @name\n      value: [(arrow_function) (function_expression)]) @definition.function)\n  (#strip! @doc \"^[\\\\s\\\\*/]+|^[\\\\s\\\\*/]$\")\n  (#select-adjacent! @doc @definition.function)\n)",
    "(assignment_expression\n  left: [\n    (identifier) @name\n    (member_expression\n      property: (property_identifier) @name)\n  ]\n  right: [(arrow_function) (function_expression)]\n) @definition.function",
    "(pair\n  key: (property_identifier) @name\n  value: [(arrow_function) (function_expression)]) @definition.function",
    "(export_statement value: (assignment_expression left: (identifier) @name right: ([\n (number)\n (string)\n (identifier)\n (undefined)\n (null)\n (new_expression)\n (binary_expression)\n (call_expression)\n]))) @definition.constant",
    NULL};

static const char *const syntax_python_tags[] = {
    "(module (expression_statement (assignment left: (identifier) @name) @definition.constant))",
    "(class_definition\n  name: (identifier) @name) @definition.class",
    "(function_definition\n  name: (identifier) @name) @definition.function",
    NULL};

static const char *const syntax_go_tags[] = {
    "(\n  (comment)* @doc\n  .\n  (function_declaration\n    name: (identifier) @name) @definition.function\n  (#strip! @doc \"^//\\\\s*\")\n  (#set-adjacent! @doc @definition.function)\n)",
    "(\n  (comment)* @doc\n  .\n  (method_declaration\n    name: (field_identifier) @name) @definition.method\n  (#strip! @doc \"^//\\\\s*\")\n  (#set-adjacent! @doc @definition.method)\n)",
    "(type_spec\n  name: (type_identifier) @name) @definition.type",
    NULL};

static const char *const syntax_rust_tags[] = {
    "(struct_item\n    name: (type_identifier) @name) @definition.class",
    "(enum_item\n    name: (type_identifier) @name) @definition.class",
    "(union_item\n    name: (type_identifier) @name) @definition.class",
    "(type_item\n    name: (type_identifier) @name) @definition.class",
    "(declaration_list\n    (function_item\n        name: (identifier) @name) @definition.method)",
    "(function_item\n    name: (identifier) @name) @definition.function",
    "(trait_item\n    name: (type_identifier) @name) @definition.interface",
    "(mod_item\n    name: (identifier) @name) @definition.module",
    "(macro_definition\n    name: (identifier) @name) @definition.macro",
    NULL};

const char *const *const SYNTAX_TAGS[SYNTAX_COUNT] = {
    [SYNTAX_C] = syntax_c_tags,
    [SYNTAX_TYPESCRIPT] = syntax_typescript_tags,
    [SYNTAX_TSX] = syntax_tsx_tags,
    [SYNTAX_JAVASCRIPT] = syntax_javascript_tags,
    [SYNTAX_PYTHON] = syntax_python_tags,
    [SYNTAX_GO] = syntax_go_tags,
    [SYNTAX_RUST] = syntax_rust_tags,
};
