/* Derived snapshot cache: .lap/snapshots/<path>.jsonl, one line per
 * snapshot {"at": entry-index, "eof_nl": bool, "content": "..."}. Purely an
 * acceleration layer — replay seeds from the nearest snapshot at or before
 * the target when one exists and replays from birth when none does; results
 * are identical either way. Deletable at any time; regenerated by rebuild.
 *
 * Policy (tunable, cache-only): snapshot when a file has accumulated more
 * than 2x its current size in delta bytes AND at least SNAP_MIN_DELTAS
 * commits since the last snapshot.
 */
#ifndef LAP_SNAP_H
#define LAP_SNAP_H

#include "idx.h"

#define SNAP_MIN_DELTAS 16

/* Emit a snapshot for rel (content = its post-commit bytes) if the budget
 * says so; resets the file's budget slot. No-op without a fresh index. */
bool snap_maybe(Arena *a, const Repo *r, Idx *idx, const char *rel,
                const char *content, size_t len, char *err, size_t errsz);

/* Replay rel to the state just after entry `upto` (which must be one of the
 * file's commits, or -1 for its latest = heads chain tail). Seeds from the
 * nearest snapshot <= upto when available. */
bool snap_replay(Arena *a, const Repo *r, const Idx *idx, const char *rel,
                 int64_t upto, Lines *out, bool *deleted);

/* Rebuild every derived cache from the log: index, shadows, snapshots
 * (fresh, per current policy), and the counters/last-hash fields of *r
 * (caller persists them with repo_state_save). */
bool snap_rebuild_all(Arena *a, Repo *r, char *err, size_t errsz);

#endif /* LAP_SNAP_H */
