/* gitignore(5) as kb reads it, and the name rules `kb add --dir` applies.
 * Expected answers are git's own (checked with `git check-ignore`). */

#include "test.h"

#include "../../src/dirscan.h"
#include "../../src/gitignore.h"

#include <string.h>

static bool ig(GitIgnore *g, const char *path, bool is_dir) {
    return gitignore_match(g, path, is_dir);
}

void test_gitignore(void) {
    t_begin("gitignore: wildmatch stars, classes and escapes");
    ASSERT_TRUE(gitignore_wildmatch("*.c", "main.c"));
    ASSERT_TRUE(!gitignore_wildmatch("*.c", "src/main.c"));
    ASSERT_TRUE(gitignore_wildmatch("src/*.c", "src/main.c"));
    ASSERT_TRUE(!gitignore_wildmatch("src/*.c", "src/a/main.c"));
    ASSERT_TRUE(gitignore_wildmatch("?.c", "a.c"));
    ASSERT_TRUE(!gitignore_wildmatch("?", "/"));
    ASSERT_TRUE(gitignore_wildmatch("[abc].md", "b.md"));
    ASSERT_TRUE(!gitignore_wildmatch("[!abc].md", "b.md"));
    ASSERT_TRUE(gitignore_wildmatch("[^abc].md", "d.md"));
    ASSERT_TRUE(gitignore_wildmatch("[a-c]x", "cx"));
    ASSERT_TRUE(!gitignore_wildmatch("[a-c]x", "dx"));
    ASSERT_TRUE(gitignore_wildmatch("[]]", "]"));
    ASSERT_TRUE(gitignore_wildmatch("a[b", "a[b"));
    ASSERT_TRUE(gitignore_wildmatch("\\*", "*"));
    ASSERT_TRUE(!gitignore_wildmatch("\\*", "x"));
    ASSERT_TRUE(gitignore_wildmatch("*", ""));

    t_begin("gitignore: ** as a whole segment spans directories");
    ASSERT_TRUE(gitignore_wildmatch("**/foo", "foo"));
    ASSERT_TRUE(gitignore_wildmatch("**/foo", "a/b/foo"));
    ASSERT_TRUE(gitignore_wildmatch("a/**/b", "a/b"));
    ASSERT_TRUE(gitignore_wildmatch("a/**/b", "a/x/y/b"));
    ASSERT_TRUE(!gitignore_wildmatch("a/**/b", "a/x/y/c"));
    ASSERT_TRUE(gitignore_wildmatch("a/**", "a/x/y"));
    ASSERT_TRUE(!gitignore_wildmatch("a/**", "a"));
    ASSERT_TRUE(gitignore_wildmatch("a**b", "axxb"));   /* not a segment: a plain star */
    ASSERT_TRUE(!gitignore_wildmatch("a**b", "a/b"));

    t_begin("gitignore: anchoring, directories only, negation, last match wins");
    Arena *a = arena_new(1 << 16);
    GitIgnore *g = gitignore_new(a);
    const char *top = "# comment\n\nbuild/\n*.log\n!keep.log\n/only-top.md\ndocs/*.tmp\n"
                      "trailing   \n\\#hash\n\\!bang\n";
    gitignore_add(g, "", top, strlen(top));
    ASSERT_TRUE(ig(g, "build", true));
    ASSERT_TRUE(ig(g, "src/build", true));
    ASSERT_TRUE(!ig(g, "build", false));            /* a file named build */
    ASSERT_TRUE(ig(g, "x.log", false));
    ASSERT_TRUE(ig(g, "deep/x.log", false));
    ASSERT_TRUE(!ig(g, "keep.log", false));
    ASSERT_TRUE(!ig(g, "deep/keep.log", false));
    ASSERT_TRUE(ig(g, "only-top.md", false));
    ASSERT_TRUE(!ig(g, "sub/only-top.md", false));
    ASSERT_TRUE(ig(g, "docs/a.tmp", false));
    ASSERT_TRUE(!ig(g, "sub/docs/a.tmp", false));    /* a middle slash anchors */
    ASSERT_TRUE(ig(g, "trailing", false));          /* trailing spaces dropped */
    ASSERT_TRUE(ig(g, "#hash", false));
    ASSERT_TRUE(ig(g, "!bang", false));
    ASSERT_TRUE(!ig(g, "comment", false));

    t_begin("gitignore: a deeper .gitignore applies below it and overrides");
    const char *sub = "!*.log\nlocal.c\n/anchored.c\n";
    gitignore_add(g, "src", sub, strlen(sub));
    ASSERT_TRUE(!ig(g, "src/x.log", false));
    ASSERT_TRUE(ig(g, "x.log", false));
    ASSERT_TRUE(ig(g, "src/local.c", false));
    ASSERT_TRUE(ig(g, "src/a/local.c", false));
    ASSERT_TRUE(!ig(g, "local.c", false));
    ASSERT_TRUE(!ig(g, "srcx/local.c", false));     /* a prefix that is not the directory */
    ASSERT_TRUE(ig(g, "src/anchored.c", false));
    ASSERT_TRUE(!ig(g, "src/a/anchored.c", false));
    const char *crlf = "win.c\r\n";
    gitignore_add(g, "", crlf, strlen(crlf));
    ASSERT_TRUE(ig(g, "win.c", false));
    arena_free(a);

    t_begin("dirscan: which names are filed, and which are generated");
    ASSERT_TRUE(dir_file_mime("main.c") != NULL);
    ASSERT_TRUE(strcmp(dir_file_mime("boot.S"), "text/x-asm") == 0);
    ASSERT_TRUE(strcmp(dir_file_mime("start.asm"), "text/x-asm") == 0);
    ASSERT_TRUE(strcmp(dir_file_mime("Makefile"), "text/x-makefile") == 0);
    ASSERT_TRUE(strcmp(dir_file_mime("view.tsx"), "application/typescript") == 0);
    ASSERT_TRUE(dir_file_mime("logo.png") == NULL);
    ASSERT_TRUE(dir_file_mime("LICENSE") == NULL);
    ASSERT_TRUE(dir_name_generated("package-lock.json"));
    ASSERT_TRUE(dir_name_generated("app.min.js"));
    ASSERT_TRUE(dir_name_generated("api.pb.go"));
    ASSERT_TRUE(!dir_name_generated("main.go"));

    t_begin("dirscan: generated markers count only near the top");
    const char *go = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n";
    ASSERT_TRUE(dir_text_generated(go, strlen(go)));
    const char *fb = "/**\n * @generated\n */\n";
    ASSERT_TRUE(dir_text_generated(fb, strlen(fb)));
    const char *doc = "# Build\n\n1\n2\n3\n4\nThe files in out/ are autogenerated.\n";
    ASSERT_TRUE(!dir_text_generated(doc, strlen(doc)));
    const char *plain = "int main(void) { return 0; }\n";
    ASSERT_TRUE(!dir_text_generated(plain, strlen(plain)));
}
